### ISSUE TITLE
Alert close button click area is too small

### ISSUE THREAD

**Issue by lbebber** [vtex/styleguide#269] opened 2018-08-17 14:58 UTC
As the title says.

To fix this, increase its padding and add negative margins.

**Comment by akaFTS** [comment] 2018-08-17 15:34
This is (probably) addressed in #246 since the "X" will become bigger

**Comment by cmdalbem** [comment] 2018-08-17 17:08
duplicate of https://github.com/vtex/styleguide/issues/246

**Closed by cmdalbem** 2018-08-17 17:08 UTC

**Comment by lbebber** [comment] 2018-08-17 17:10
@akaFTS @cmdalbem Show, só lembrar de fazer isso do padding/margem negativa, só aumentar o icone em si não é o suficiente
